version: "2"

# Ограничение на дублирующиеся предупреждения
issues:
  max-same-issues: 50

# Форматтеры: автоматически исправляют стиль
formatters:
  enable:
    - goimports  # Группирует импорты и убирает неиспользуемые
    - golines    # Автоматически обрезает строки до 120 символов

  settings:
    goimports:
      local-prefixes:
        - github.com/hello-larin/avito-2025-autumn
    golines:
      max-len: 120

linters:
  enable:
    - errcheck      # Проверяет, что ошибки не игнорируются
    - govet         # Встроенный анализатор Go: Printf, race, shadow и т.д.
    - staticcheck   # Мощный статический анализ — находит баги, устаревшие API
    - unused        # Находит неиспользуемые переменные, функции, пакеты

    - gosec         # Ищет уязвимости: SQLi, секреты, слабые хеши

    - revive        # Современная замена golint — проверяет комментарии, имена
    - godoclint     # Проверяет качество документации (пакеты, функции)
    - reassign      # Запрещает переопределять переменные пакета (предотвращает скрытые баги)

  exclusions:
    # Блокируем ошибки revive о комментариях при экспорте
    rules:
      - text: 'should have a package comment'
        linters: [ revive ]
      - text: 'exported \S+ \S+ should have comment( \(or a comment on this block\))? or be unexported'
        linters: [ revive ]
      - text: 'package comment should be of the form ".+"'
        source: '// ?(nolint|TODO)'
        linters: [ revive ]
      - text: 'comment on exported \S+ \S+ should be of the form ".+"'
        source: '// ?(nolint|TODO)'
        linters: [ revive, staticcheck ]